### ISSUE TITLE
数据库文件

### ISSUE THREAD

**Issue by Yuakeo** [handy-git/HandyLib-Doc#2]
File langFile = new File(InitApi.PLUGIN.getDataFolder(), "storage.yml");
if (!langFile.exists()) {
      InitApi.PLUGIN.saveResource("storage.yml", false);
}
希望可以自定义这个文件,而不是一定要在storage.yml中

**Comment by handy-git** [comment]
在多年服主经验中,重复无用的配置会很令人头疼

所以固定一个大家熟知的名字和简单的配置,避免增加学习成本是一个最优选
